GitHubApi/Models/Keyword.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GitHubApi.Models
{
    public class Keyword
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

GitHubApi/Models/Repo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Runtime.Serialization;

namespace GitHubApi.Models
{
    [DataContract(Name = "repo")]
    [Table("Repo")]
    public class Repo
    {
        [Key]
        public int RepoID { get; set; }

        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "name")]
        public string Name { get; set; }

        [DataMember(Name = "description")]
        [MaxLength(500)]
        public string Description { get; set; }

        [DataMember(Name = "forks")]
        public int Forks { get; set; }

        [DataMember(Name = "stargazers_count")]
        public int Stars { get; set; }

        [DataMember(Name = "html_url")]
        public string Url { get; set; }
    }
}

GitHubApi/Models/RepoItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace GitHubApi.Models
{
    [DataContract(Name = "RepoItems")]
    public class RepoItems
    {
        [DataMember(Name = "items")]
        public List<Repo> Item { get; set; }

        [DataMember(Name = "total_count")]
        public int Total { get; set; }
    }
}

GitHubApi/Controllers/ValuesController.cs
using GitHubApi.Data;
using Microsoft.AspNetCore.Mvc;

namespace GitHubApi.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {

        // private RepoRepository _repoRepository = new RepoRepository();
        public bool HasWord;
        //private Context _context = null;
        private readonly Context _context;

        private bool _disposed = false;

        // Making sure we are creating just one instance of the context class
        public ValuesController(Context context)
        {
            //_context = new Context();
            _context = context;

        }


        // GET api/values
        [HttpGet]
        public ActionResult Index(string query = "Angular")
        {
            var repositories = ApiRepoRepository.GetRepositories(query).Result;

            var Keywords = DbKeywordRepository.GetKeyword(_context);

            foreach (var el in Keywords)
            {
                if (el.Name == query)
                {
                    HasWord = true;
                }

            }

            if (!HasWord)
            {
                DbKeywordRepository.AddKeyword(_context, query);
                DbRepoRepository.AddRepository(_context, repositories);
            }
          

            return View(repositories.Item);
        }

        //GET api/values/5
        [HttpGet("{id}")]
        public ActionResult Details(int id)
        {
            var repositories = ApiRepoRepository.GetRepositoriesById(id).Result;
            return View(repositories);
            //return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }

        [HttpGet("search")]
        public ActionResult Search(string query)
        {

            var Repos = DbRepoRepository.GetRepositories(_context);
            return View(Repos);
            

        }

        

        protected override void Dispose(bool disposing)
        {

            if (_disposed)
                return;

            if (disposing)
            {
                _context.Dispose();
            }

            _disposed = true;

            base.Dispose(disposing);
        }

    }
}

GitHubApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GitHubWebApi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">GitHubWebApi</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Values")</li>
                    <li>@Html.ActionLink("View Database", "Search", "Values")</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - GitHubWebApi</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

GitHubApi/Views/Values/Details.cshtml
@model GitHubApi.Models.Repo

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Repo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forks)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forks)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stars)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd>
            <a href="@Html.DisplayFor(model => model.Url)" target="_blank">@Html.DisplayFor(model => model.Url)</a>
        </dd>
    </dl>
</div>
<div>

    @Html.ActionLink("Back to List", "Index", "Values")
</div>

GitHubApi/Views/Values/Edit.cshtml
@model GitHubApi.Models.Repo

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<div>
    <h4>Repo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forks)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forks)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Stars)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Stars)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

GitHubApi/Views/Values/Index.cshtml
@model IEnumerable<GitHubApi.Models.Repo>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    @*<a asp-action="Create">Create New</a>*@
    <br/>
</p>
<form asp-controller="Values" asp-action="Index">
    <p>
        Search: <input type="text" name="query">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Forks)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Stars)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Forks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stars)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("View Details", "Details", "values", new { id = item.Id }, null)
                @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@

            </td>
        </tr>
}
    </tbody>
</table>

GitHubApi/Views/Values/Search.cshtml
@model IEnumerable<GitHubApi.Models.Repo>

@{
    ViewData["Title"] = "List DB";
}

<h2>Index</h2>

<p>
    @*<a asp-action="Create">Create New</a>*@
    <br />
</p>
<form asp-controller="Values" asp-action="Index">
    <p>

    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Forks)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stars)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Forks)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stars)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                    @Html.ActionLink("View Details", "Details", "values", new { id = item.Id }, null)
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@

                </td>
            </tr>
        }
    </tbody>
</table>